name: Hostinger SSH Deployment
on:
  push:
    branches: [main]
  workflow_call:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.2"
      # - name: Install Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: "16.x"
      # - name: Install npm dependencies
      #   run: npm install
      # - name: Run build task
      #   run: npm run production
      - name: Test SSH Connection
        run: ssh -v -p 65002 ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} "echo 'SSH Connection Successful'"
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/hostinger
          chmod 600 ~/.ssh/hostinger
          echo "Host your-server-ip" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/hostinger" >> ~/.ssh/config
          echo "  IdentitiesOnly yes" >> ~/.ssh/config
      - name: Remove ED25519 Key (if exists)
        run: ssh-add -d ~/.ssh/id_ed25519 || true
      - name: Delete Known Hosts (if exists)
        run: |
          rm -f ~/.ssh/known_hosts
          touch ~/.ssh/known_hosts
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SCRIPT_BEFORE: ls
          ARGS: "-avz --delete"
          EXCLUDE: "/.git/, /.github/, /.hygen/, /node_modules/"
          TARGET: public_html/wp-content/themes/tailpress-master
